### ISSUE TITLE
SnapshotDoesNotExistException on Azure Pipelines ubuntu-20.04 Agent

### ISSUE THREAD

**Issue by nganbread** [theramis/Snapper#85]
**Describe the bug**
Unsure if this affects all linux/ubuntu systems, or if it's specific to Azure Pipelines, but I receive the following when running CI Snapper tests

```
Snapper.Exceptions.SnapshotDoesNotExistException : A snapshot does not exist.  Run the test outside of a CI environment to create a snapshot.
```

Snapshots work perfectly on Windows

**To Reproduce**
1. Create a test project using Snapper
2. Create an azure pipeline using an ubuntu-20.04 agent
3. Add the default dotnet test task to the pipeline 

**Additional context**
Snapper Version: 2.3.0
Operation System: ubuntu-20.04
.Net Version: 6

![image](https://user-images.githubusercontent.com/1046436/135732623-c789bab9-47ff-4a29-8a5d-1ffdafaf293e.png)

```
steps:
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*.[Tt]ests.*csproj'
    arguments: '--configuration $(BuildConfiguration)'
    testRunTitle: 'Backend Tests'
    workingDirectory: backend
```
